import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="w-full h-20 fixed top-0 left-0 bg-black z-101">
            <nav className="container flex items-center justify-between h-full z-100">
              <ul>
                <li>
                  <Link href="/">Home</Link>
                </li>
              </ul>
            </nav>
          </header>
          <main className="w-screen h-screen pt-20">{children}</main>
          <footer></footer>
        </Providers>
      </body>
    </html>
  );
}
